#!/bin/bash

# PATHS
BASE=$PWD
DOCKER_COMPOSE_PATH="$BASE/docker-compose.yml"
SERVER_PATH="$BASE/server"
# this bash script is a work in progress

function runInNewTab() {
  osascript -e 'tell application "Terminal" to activate' \
            -e 'tell application "System Events" to keystroke "t" using {command down}' \
            -e 'delay 1' \
            -e 'tell application "Terminal" to do script "'"$1"'" in selected tab of the front window'
}

function constructserver() {
  runInNewTab "docker build -t server $BASE"
}

function composeAndMigrate() {
  runInNewTab "docker-compose run server npm run migrate"
}

function startUp() {
  runInNewTab "docker-compose -f $DOCKER_COMPOSE_PATH up --build"
}

function launchDev() {
  runInNewTab "docker-compose up postgres" &&
  sleep .5 &&
  runInNewTab "cd $SERVER_PATH; npm run pm2"
}


case $1 in
  build-server)
    constructserver
  ;;
  migrate)
    composeAndMigrate
  ;;
  start)
    startUp
  ;;
  launch-dev)
    launchDev
  ;;
  "quit")
    docker-compose -f $DOCKER_COMPOSE_PATH down &&
    osascript -e 'tell application "Terminal" to close every window' \
              -e 'tell application "Terminal" to activate' \
              -e 'tell application "Terminal" to do script "'"cd $BASE"'"'
  ;;
  *)
    printf "\n\nPlease specify a command\n\n\n
    specify one of the following:\n\n
    \tbuild-server\t- Builds the docker image of the server
    \tmigrate\t- Runs migrations within the docker container
    \tstart\t- Launches local dev environment
    \tquit\t- quits\nPlease"
  ;;
esac
